---
# Copyright (c) 2016 FUJITSU LIMITED
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not used this file except in compliance with the License. You may obtain
# a copy of the License at:
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#

- name: download scala
  shell: curl https://downloads.typesafe.com/scala/2.11.7/scala-2.11.7.deb > {{home_dir}}/scala.deb

- name: install Scala
  become: yes
  command: dpkg -i {{home_dir}}/scala.deb

- name: download sbt.list
  become: yes
  shell: echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list

- name: download sbt's public key 
  become: yes
  shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823

- name: update apt-get
  become: yes
  apt: update_cache=yes

- name: install sbt
  become: yes
  apt: name=sbt
